# Eventually you could have attributes for the model resources
resources:
  Application:
  Artifact:
  AwsRdsInstance:
  AwsService:
  Container:
  Deployment:
  Environment:
  KubeCluster:
  Manifest:
  Region:
  Secret:
  Vault:
  VersionTag:
  CloudProvider:
