# Eventually you could have attributes for the model resources
resources:
  CloudProvider:
  Region:
  Ami:
  Vpc:
  Ec2:
  Registery:
  Application:
  Container:
  Scan:
  KnowledgeBase:
  Vulnerability:
